server:
  port: 8080

spring:
  application:
    name: yudao-module-oa
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

oa:
  auth:
    mode: dev-fixed
  crypto:
    aes-key: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=

logging:
  level:
    cn.iocoder.yudao.module.oa: INFO
