/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountSelect: typeof import('./components/selectors/AccountSelect.vue')['default']
    CompanySelect: typeof import('./components/selectors/CompanySelect.vue')['default']
    ContentWrap: typeof import('./components/ContentWrap.vue')['default']
    DictSelect: typeof import('./components/DictSelect.vue')['default']
    IpGroupTreeSelect: typeof import('./components/selectors/IpGroupTreeSelect.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    PhoneSelect: typeof import('./components/selectors/PhoneSelect.vue')['default']
    RealNameSelect: typeof import('./components/selectors/RealNameSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimCardSelect: typeof import('./components/selectors/SimCardSelect.vue')['default']
    TableSearch: typeof import('./components/TableSearch.vue')['default']
    UserSelect: typeof import('./components/selectors/UserSelect.vue')['default']
  }
}
