#!/usr/bin/env python3
"""Generate V23 seed analytics SQL fragments."""
from datetime import date, timedelta
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src/main/resources/db/migration/_v23_generated.sql"


def gen_follower(account_id: int, start_base: int, start: date, end: date) -> list[str]:
    lines = []
    d = start
    base = start_base
    while d <= end:
        growth = 300 + (account_id % 7) * 20 + (d.day % 5) * 10
        unfollow = 80 + (d.day % 3) * 10
        net = growth - unfollow
        base += net
        rate = round(net / max(base - net, 1), 4)
        lines.append(
            f"(1, {account_id}, '{d}', {base}, {growth}, {unfollow}, {net}, {rate}, 'seed-analytics')"
        )
        d += timedelta(days=1)
    return lines


def gen_status_log(account_id: int, start: date, end: date, base_followers: int) -> list[str]:
    lines = []
    d = start
    followers = base_followers
    statuses = ["NORMAL", "NORMAL", "NORMAL", "WARNING", "NORMAL"]
    idx = 0
    while d <= end:
        status = statuses[idx % len(statuses)]
        lines.append(f"(1, {account_id}, '{d}', '{status}', {followers}, 'seed-analytics', 'seed-analytics')")
        followers += 350
        idx += 1
        d += timedelta(days=1)
    return lines


def gen_content_rows() -> list[str]:
    rows = []
    accounts = [
        (9001, "WECHAT_OFFICIAL", "ARTICLE"),
        (9002, "WECHAT_OFFICIAL", "ARTICLE"),
        (9006, "DOUYIN", "VIDEO"),
        (9007, "DOUYIN", "VIDEO"),
        (9010, "WECHAT_OFFICIAL", "ARTICLE"),
        (9003, "WECHAT_OFFICIAL", "ARTICLE"),
        (9004, "WECHAT_VIDEO", "VIDEO"),
        (9008, "KUAISHOU", "VIDEO"),
    ]
    cid = 9350
    for i in range(22):
        acc, plat, ctype = accounts[i % len(accounts)]
        day = 1 + (i % 28)
        read_count = 1000 + i * 3500
        like_count = 50 + i * 120
        is_hit = 1 if read_count >= 50000 else 0
        rows.append(
            f"({cid}, 1, {acc}, 'SEED-分析内容-{i+1:02d}', '{plat}', '{ctype}', "
            f"'2026-05-{day:02d} 10:00:00', {read_count}, {like_count}, {10+i}, {5+i}, "
            f"{is_hit}, 'API', 'PUBLISHED', 'seed-analytics', 'seed-analytics')"
        )
        cid += 1
    return rows


def main():
    end = date(2026, 6, 8)
    start = date(2026, 3, 11)

    f9001 = gen_follower(9001, 91000, start, date(2026, 5, 9))
    f9002 = gen_follower(9002, 50000, start, end)
    f9010 = gen_follower(9010, 30000, start, end)

    s9001 = gen_status_log(9001, start, end, 91000)
    s9002 = gen_status_log(9002, start, end, 50000)
    s9010 = gen_status_log(9010, start, end, 30000)

    content = gen_content_rows()

    parts = [
        "-- AUTO-GENERATED by scripts/gen_v23_seed.py",
        "",
        "-- follower_daily supplement for 9001 (2026-03-11 ~ 2026-05-09)",
        "INSERT INTO oa_follower_daily (tenant_id, account_id, stat_date, follower_count, new_follower, unfollow_count, net_growth, growth_rate, creator) VALUES",
        ",\n".join(f9001) + ";",
        "",
        "-- follower_daily 9002 full 90 days",
        "INSERT INTO oa_follower_daily (tenant_id, account_id, stat_date, follower_count, new_follower, unfollow_count, net_growth, growth_rate, creator) VALUES",
        ",\n".join(f9002) + ";",
        "",
        "-- follower_daily 9010 full 90 days",
        "INSERT INTO oa_follower_daily (tenant_id, account_id, stat_date, follower_count, new_follower, unfollow_count, net_growth, growth_rate, creator) VALUES",
        ",\n".join(f9010) + ";",
        "",
        "-- oa_content analytics samples (22 rows)",
        "INSERT INTO oa_content (id, tenant_id, account_id, title, platform_type, content_type, publish_time, read_count, like_count, comment_count, forward_count, is_hit, data_source, status, creator, updater) VALUES",
        ",\n".join(content) + ";",
        "",
        "-- oa_account_status_log 90-day samples",
        "INSERT INTO oa_account_status_log (tenant_id, account_id, stat_date, status, follower_count, creator, updater) VALUES",
        ",\n".join(s9001 + s9002 + s9010) + ";",
    ]

    # content_daily for first 5 contents, last 30 days
    cd_lines = []
    for content_id in range(9350, 9355):
        d = date(2026, 5, 10)
        reads = 5000
        while d <= end:
            reads += 200 + (d.day % 7) * 50
            cd_lines.append(f"(1, {content_id}, '{d}', {reads}, {reads // 3}, 'seed-analytics')")
            d += timedelta(days=1)
    parts.extend([
        "",
        "-- oa_content_daily trend samples",
        "INSERT INTO oa_content_daily (tenant_id, content_id, stat_date, read_count, play_count, creator) VALUES",
        ",\n".join(cd_lines) + ";",
    ])

    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUT} ({len(parts)} sections)")


if __name__ == "__main__":
    main()
