#!/usr/bin/env python3
"""Generate record-flyway-history.sql with Flyway-compatible CRC32 checksums.

Run from repo root:
  python scripts/integration-config/gen-ops-flyway-history.py

Requires Flyway SQL source directory (185 files). Set FLYWAY_SRC or use default submodule path:
  football-backend-saas/football-module-ops/football-module-ops-server/src/main/resources/db/migration

Output: scripts/integration-config/ops-flyway-record-history.sql
"""
from __future__ import annotations

import os
import re
import sys
import zlib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
INTEG_DIR = Path(__file__).resolve().parent
ORDER_FILE = INTEG_DIR / "ops-flyway-migration-order.txt"
OUT_FILE = INTEG_DIR / "ops-flyway-record-history.sql"

DEFAULT_FLYWAY_SRC = (
    REPO_ROOT
    / "football-backend-saas"
    / "football-module-ops"
    / "football-module-ops-server"
    / "src"
    / "main"
    / "resources"
    / "db"
    / "migration"
)


def flyway_sql_dir() -> Path:
    env = os.environ.get("FLYWAY_SRC")
    if env:
        return Path(env)
    legacy = REPO_ROOT / "docs/deploy/ops-greenfield-production/01-database-shenyu-ops/flyway-sql"
    if legacy.is_dir():
        return legacy
    return DEFAULT_FLYWAY_SRC


def signed_crc32(path: Path) -> int:
    value = zlib.crc32(path.read_bytes()) & 0xFFFFFFFF
    return value if value < 0x80000000 else value - 0x100000000


def parse_sql_entry(filename: str, sql_dir: Path) -> dict:
    match = re.match(r"^V(\d+)__(.+)\.sql$", filename)
    if not match:
        raise ValueError(f"Invalid Flyway SQL filename: {filename}")
    path = sql_dir / filename
    if not path.exists():
        raise FileNotFoundError(f"Missing SQL: {path}")
    return {
        "version": match.group(1),
        "description": match.group(2).replace("_", " "),
        "type": "SQL",
        "script": filename,
        "checksum": signed_crc32(path),
    }


def main() -> int:
    sql_dir = flyway_sql_dir()
    if not sql_dir.is_dir():
        print(f"ERROR: Flyway source not found: {sql_dir}", file=sys.stderr)
        print("Set FLYWAY_SRC to migration directory.", file=sys.stderr)
        return 1

    entries: list[dict] = []
    for line in ORDER_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.endswith(".java"):
            continue
        entries.append(parse_sql_entry(line, sql_dir))

    lines = [
        "-- =============================================================================",
        "-- flyway_schema_history — idempotent INSERT (186 SQL migrations, V113 Java excluded)",
        f"-- Generated by gen-ops-flyway-history.py from {sql_dir.name}/",
        "-- =============================================================================",
        "SET NAMES utf8mb4;",
        "",
        "CREATE TABLE IF NOT EXISTS flyway_schema_history (",
        "    installed_rank INT NOT NULL,",
        "    version VARCHAR(50),",
        "    description VARCHAR(200) NOT NULL,",
        "    type VARCHAR(20) NOT NULL,",
        "    script VARCHAR(1000) NOT NULL,",
        "    checksum INT,",
        "    installed_by VARCHAR(100) NOT NULL,",
        "    installed_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,",
        "    execution_time INT NOT NULL,",
        "    success TINYINT NOT NULL,",
        "    PRIMARY KEY (installed_rank)",
        ") ENGINE=InnoDB;",
        "",
    ]

    for rank, entry in enumerate(entries, start=1):
        lines.append(
            f"INSERT INTO flyway_schema_history "
            f"(installed_rank, version, description, type, script, checksum, installed_by, execution_time, success) "
            f"SELECT {rank}, '{entry['version']}', '{entry['description']}', '{entry['type']}', "
            f"'{entry['script']}', {entry['checksum']}, 'manual-dba-greenfield', 0, 1 "
            f"FROM DUAL WHERE NOT EXISTS ("
            f"SELECT 1 FROM flyway_schema_history WHERE version = '{entry['version']}' AND success = 1);"
        )

    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(REPO_ROOT)} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
