CREATE TABLE IF NOT EXISTS author_user (
  id bigint NOT NULL AUTO_INCREMENT,
  parent_id bigint NULL,
  user_id bigint NULL,
  mobile varchar(255) NULL,
  nickname varchar(255) NULL,
  avatar_url varchar(255) NULL,
  birthday date NULL,
  sex int NULL,
  province_id int NULL,
  city_id int NULL,
  adept_at json NULL,
  sort_num int NULL,
  status int NULL,
  tags json NULL,
  welcome_msg varchar(255) NULL,
  cs_wechat varchar(255) NULL,
  cs_wecom varchar(255) NULL,
  recommend int NULL,
  recommend_start_time datetime NULL,
  recommend_end_time datetime NULL,
  author_source int NULL,
  author_real_source int NULL,
  author_level int NULL,
  wechat_account varchar(255) NULL,
  qq_account varchar(255) NULL,
  recommend_user_id int NULL,
  intro varchar(255) NULL,
  remark varchar(255) NULL,
  msg_push_threshold int NULL,
  is_signed int NULL,
  order_ratio decimal(20,4) NULL,
  withdrawal_fee_ratio decimal(20,4) NULL,
  min_withdrawal_amount decimal(20,4) NULL,
  max_withdrawal_amount decimal(20,4) NULL,
  withdrawal_period int NULL,
  total_articles int NULL,
  hit_rate decimal(20,4) NULL,
  recent_articles int NULL,
  recent_hits int NULL,
  consecutive_hits int NULL,
  last_login_ip varchar(255) NULL,
  last_login_time datetime NULL,
  register_ip varchar(255) NULL,
  fans int NULL,
  on_sale_num int NULL,
  apply_id bigint NULL,
  rtp decimal(20,4) NULL,
  private_status int NULL,
  performance_show int NULL,
  is_attention int NULL,
  consume int NULL,
  captive_push_account bigint NULL,
  captive_push_account_name varchar(255) NULL,
  live_id bigint NULL,
  report_push int NULL,
  alarm_account_count int NULL,
  push_mode int NULL,
  ban_push int NULL,
  access_mode int NULL,
  report_name varchar(255) NULL,
  tenant_id bigint NOT NULL DEFAULT 0,
  creator varchar(64) DEFAULT NULL,
  create_time datetime DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT NULL,
  update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
