-- V126: Add comments for remaining tables and columns
-- Generated by script

-- ========== oa_account_status_log ==========
ALTER TABLE oa_account_status_log COMMENT='账号状态日志表';
ALTER TABLE oa_account_status_log MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_account_status_log MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_account_status_log MODIFY COLUMN account_id bigint NOT NULL COMMENT '账号ID';
ALTER TABLE oa_account_status_log MODIFY COLUMN stat_date date NOT NULL COMMENT '统计日期';
ALTER TABLE oa_account_status_log MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '状态';
ALTER TABLE oa_account_status_log MODIFY COLUMN follower_count bigint NOT NULL DEFAULT '0' COMMENT '粉丝数';
ALTER TABLE oa_account_status_log MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_account_status_log MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_account_status_log MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_account_status_log MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_account_status_log MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_ai_model_config ==========
ALTER TABLE oa_ai_model_config COMMENT='AI模型配置表';
ALTER TABLE oa_ai_model_config MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_ai_model_config MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_ai_model_config MODIFY COLUMN model_name varchar(128) NOT NULL COMMENT '模型名称';
ALTER TABLE oa_ai_model_config MODIFY COLUMN model_id varchar(100) DEFAULT NULL COMMENT '模型ID';
ALTER TABLE oa_ai_model_config MODIFY COLUMN model_type varchar(64) DEFAULT NULL COMMENT '模型类型';
ALTER TABLE oa_ai_model_config MODIFY COLUMN api_endpoint varchar(512) DEFAULT NULL COMMENT 'API端点地址';
ALTER TABLE oa_ai_model_config MODIFY COLUMN api_key_encrypted varchar(512) DEFAULT NULL COMMENT 'API密钥(加密)';
ALTER TABLE oa_ai_model_config MODIFY COLUMN max_tokens int DEFAULT NULL COMMENT '最大Token数';
ALTER TABLE oa_ai_model_config MODIFY COLUMN timeout int DEFAULT '60' COMMENT '超时时间';
ALTER TABLE oa_ai_model_config MODIFY COLUMN is_default tinyint NOT NULL DEFAULT '0' COMMENT '是否默认';
ALTER TABLE oa_ai_model_config MODIFY COLUMN conn_status varchar(20) DEFAULT 'DISCONNECTED' COMMENT '连接状态';
ALTER TABLE oa_ai_model_config MODIFY COLUMN temperature decimal(4,2) DEFAULT NULL COMMENT '温度参数';
ALTER TABLE oa_ai_model_config MODIFY COLUMN top_p decimal(4,2) DEFAULT NULL COMMENT 'Top-P采样';
ALTER TABLE oa_ai_model_config MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态';
ALTER TABLE oa_ai_model_config MODIFY COLUMN remark varchar(512) DEFAULT NULL COMMENT '备注';
ALTER TABLE oa_ai_model_config MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_ai_model_config MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_ai_model_config MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_ai_model_config MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_ai_model_config MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_ai_prompt_config ==========
ALTER TABLE oa_ai_prompt_config COMMENT='AI提示词配置表';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN template_name varchar(128) NOT NULL COMMENT '模板名称';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN version varchar(20) NOT NULL DEFAULT 'v1' COMMENT '版本';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN scene varchar(64) DEFAULT NULL COMMENT '场景';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN prompt_content text NOT NULL COMMENT '提示词内容';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN variable_desc text DEFAULT NULL COMMENT '变量描述';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN temperature decimal(4,2) DEFAULT NULL COMMENT '温度参数';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN remark varchar(512) DEFAULT NULL COMMENT '备注';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN content_type varchar(64) DEFAULT NULL COMMENT '内容类型';
ALTER TABLE oa_ai_prompt_config MODIFY COLUMN document_type varchar(64) DEFAULT NULL COMMENT '文档类型';

-- ========== oa_aochuang_friend ==========
ALTER TABLE oa_aochuang_friend COMMENT='奥创好友列表';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN personal_wechat_id bigint NOT NULL COMMENT '个人微信ID';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN aochuang_wechat_account_id varchar(64) NOT NULL COMMENT '奥创微信账号ID';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN aochuang_friend_id varchar(64) NOT NULL COMMENT '奥创好友ID';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN wechat_id varchar(64) DEFAULT NULL COMMENT '微信ID';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN alias varchar(64) DEFAULT NULL COMMENT '别名';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN nickname varchar(200) DEFAULT NULL COMMENT '昵称';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN avatar varchar(512) DEFAULT NULL COMMENT '头像';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN remark varchar(200) DEFAULT NULL COMMENT '备注';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN synced_at timestamp DEFAULT NULL COMMENT '同步时间';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_aochuang_friend MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_aochuang_message ==========
ALTER TABLE oa_aochuang_message COMMENT='奥创消息记录表';
ALTER TABLE oa_aochuang_message MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_aochuang_message MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_aochuang_message MODIFY COLUMN personal_wechat_id bigint NOT NULL COMMENT '个人微信ID';
ALTER TABLE oa_aochuang_message MODIFY COLUMN aochuang_wechat_account_id varchar(64) NOT NULL COMMENT '奥创微信账号ID';
ALTER TABLE oa_aochuang_message MODIFY COLUMN aochuang_message_id varchar(64) NOT NULL COMMENT '奥创消息ID';
ALTER TABLE oa_aochuang_message MODIFY COLUMN aochuang_friend_id varchar(64) DEFAULT NULL COMMENT '奥创好友ID';
ALTER TABLE oa_aochuang_message MODIFY COLUMN msg_type varchar(32) DEFAULT NULL COMMENT '消息类型';
ALTER TABLE oa_aochuang_message MODIFY COLUMN direction varchar(16) NOT NULL COMMENT '消息方向';
ALTER TABLE oa_aochuang_message MODIFY COLUMN content text DEFAULT NULL COMMENT '内容';
ALTER TABLE oa_aochuang_message MODIFY COLUMN message_time timestamp NOT NULL COMMENT '消息时间';
ALTER TABLE oa_aochuang_message MODIFY COLUMN synced_at timestamp DEFAULT NULL COMMENT '同步时间';
ALTER TABLE oa_aochuang_message MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_aochuang_message MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_aochuang_message MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_aochuang_message MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_aochuang_message MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_aochuang_sync_cursor ==========
ALTER TABLE oa_aochuang_sync_cursor COMMENT='奥创同步游标表';
ALTER TABLE oa_aochuang_sync_cursor MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_aochuang_sync_cursor MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_aochuang_sync_cursor MODIFY COLUMN sync_type varchar(32) NOT NULL COMMENT '同步类型';
ALTER TABLE oa_aochuang_sync_cursor MODIFY COLUMN aochuang_wechat_account_id varchar(64) NOT NULL COMMENT '奥创微信账号ID';
ALTER TABLE oa_aochuang_sync_cursor MODIFY COLUMN personal_wechat_id bigint NOT NULL COMMENT '个人微信ID';
ALTER TABLE oa_aochuang_sync_cursor MODIFY COLUMN cursor_value varchar(256) DEFAULT NULL COMMENT '游标值';
ALTER TABLE oa_aochuang_sync_cursor MODIFY COLUMN last_sync_at timestamp DEFAULT NULL COMMENT '最后同步时间';
ALTER TABLE oa_aochuang_sync_cursor MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_aochuang_sync_cursor MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_aochuang_sync_cursor MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_aochuang_sync_cursor MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_aochuang_sync_cursor MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_aocreate_account ==========
ALTER TABLE oa_aocreate_account COMMENT='奥创账号表';
ALTER TABLE oa_aocreate_account MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_aocreate_account MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_aocreate_account MODIFY COLUMN aocreate_api_id bigint NOT NULL COMMENT '奥创API配置ID';
ALTER TABLE oa_aocreate_account MODIFY COLUMN account_name varchar(100) NOT NULL COMMENT '账号名称';
ALTER TABLE oa_aocreate_account MODIFY COLUMN aochuang_account_id varchar(64) NOT NULL COMMENT 'Aochuang AccountID';
ALTER TABLE oa_aocreate_account MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态';
ALTER TABLE oa_aocreate_account MODIFY COLUMN last_device_sync_at timestamp DEFAULT NULL COMMENT '最后设备同步时间';
ALTER TABLE oa_aocreate_account MODIFY COLUMN conn_status varchar(32) DEFAULT NULL COMMENT '连接状态';
ALTER TABLE oa_aocreate_account MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_aocreate_account MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_aocreate_account MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_aocreate_account MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_aocreate_account MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_aocreate_api ==========
ALTER TABLE oa_aocreate_api COMMENT='奥创API配置表';
ALTER TABLE oa_aocreate_api MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_aocreate_api MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_aocreate_api MODIFY COLUMN api_url varchar(255) NOT NULL COMMENT 'API地址';
ALTER TABLE oa_aocreate_api MODIFY COLUMN app_id varchar(100) NOT NULL COMMENT '应用ID';
ALTER TABLE oa_aocreate_api MODIFY COLUMN app_secret_encrypted varchar(512) DEFAULT NULL COMMENT '应用密钥(加密)';
ALTER TABLE oa_aocreate_api MODIFY COLUMN token_encrypted varchar(512) DEFAULT NULL COMMENT '令牌(加密)';
ALTER TABLE oa_aocreate_api MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态';
ALTER TABLE oa_aocreate_api MODIFY COLUMN daily_quota int NOT NULL DEFAULT '10000' COMMENT '每日配额';
ALTER TABLE oa_aocreate_api MODIFY COLUMN current_usage int NOT NULL DEFAULT '0' COMMENT '当前用量';
ALTER TABLE oa_aocreate_api MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_aocreate_api MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_aocreate_api MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_aocreate_api MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_aocreate_api MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_collect_config ==========
ALTER TABLE oa_collect_config COMMENT='采集配置表';
ALTER TABLE oa_collect_config MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_collect_config MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_collect_config MODIFY COLUMN scope varchar(32) NOT NULL COMMENT '范围';
ALTER TABLE oa_collect_config MODIFY COLUMN config_name varchar(128) NOT NULL COMMENT '配置名称';
ALTER TABLE oa_collect_config MODIFY COLUMN sub_type varchar(32) DEFAULT NULL COMMENT '子类型';
ALTER TABLE oa_collect_config MODIFY COLUMN platform_type varchar(64) DEFAULT NULL COMMENT '平台类型';
ALTER TABLE oa_collect_config MODIFY COLUMN account_id bigint DEFAULT NULL COMMENT '账号ID';
ALTER TABLE oa_collect_config MODIFY COLUMN app_id varchar(100) DEFAULT NULL COMMENT '应用ID';
ALTER TABLE oa_collect_config MODIFY COLUMN app_secret_encrypted varchar(512) DEFAULT NULL COMMENT '应用密钥(加密)';
ALTER TABLE oa_collect_config MODIFY COLUMN cookie text DEFAULT NULL COMMENT 'Cookie';
ALTER TABLE oa_collect_config MODIFY COLUMN auth_token_encrypted varchar(512) DEFAULT NULL COMMENT '认证令牌(加密)';
ALTER TABLE oa_collect_config MODIFY COLUMN field_mapping text DEFAULT NULL COMMENT '字段映射';
ALTER TABLE oa_collect_config MODIFY COLUMN is_live tinyint NOT NULL DEFAULT '0' COMMENT '是否直播';
ALTER TABLE oa_collect_config MODIFY COLUMN db_host varchar(50) DEFAULT NULL COMMENT '数据库主机';
ALTER TABLE oa_collect_config MODIFY COLUMN db_port int DEFAULT '3306' COMMENT '数据库端口';
ALTER TABLE oa_collect_config MODIFY COLUMN db_name varchar(100) DEFAULT NULL COMMENT '数据库名';
ALTER TABLE oa_collect_config MODIFY COLUMN db_username varchar(100) DEFAULT NULL COMMENT '数据库用户名';
ALTER TABLE oa_collect_config MODIFY COLUMN db_password_encrypted varchar(512) DEFAULT NULL COMMENT '数据库密码(加密)';
ALTER TABLE oa_collect_config MODIFY COLUMN table_name varchar(100) DEFAULT 'pay_all_order' COMMENT '表名';
ALTER TABLE oa_collect_config MODIFY COLUMN sync_mode varchar(20) DEFAULT 'INCREMENTAL' COMMENT '同步模式';
ALTER TABLE oa_collect_config MODIFY COLUMN conn_status varchar(20) DEFAULT 'DISCONNECTED' COMMENT '连接状态';
ALTER TABLE oa_collect_config MODIFY COLUMN collect_frequency varchar(32) DEFAULT NULL COMMENT '采集频率';
ALTER TABLE oa_collect_config MODIFY COLUMN collect_method varchar(32) DEFAULT NULL COMMENT '采集方式';
ALTER TABLE oa_collect_config MODIFY COLUMN api_url varchar(512) DEFAULT NULL COMMENT 'API地址';
ALTER TABLE oa_collect_config MODIFY COLUMN api_key_encrypted varchar(512) DEFAULT NULL COMMENT 'API密钥(加密)';
ALTER TABLE oa_collect_config MODIFY COLUMN request_method varchar(16) DEFAULT NULL COMMENT '请求方法';
ALTER TABLE oa_collect_config MODIFY COLUMN request_params text DEFAULT NULL COMMENT '请求参数';
ALTER TABLE oa_collect_config MODIFY COLUMN response_mapping text DEFAULT NULL COMMENT '响应映射';
ALTER TABLE oa_collect_config MODIFY COLUMN collect_fields text DEFAULT NULL COMMENT '采集字段';
ALTER TABLE oa_collect_config MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态';
ALTER TABLE oa_collect_config MODIFY COLUMN remark varchar(512) DEFAULT NULL COMMENT '备注';
ALTER TABLE oa_collect_config MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_collect_config MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_collect_config MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_collect_config MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_collect_config MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_collect_log ==========
ALTER TABLE oa_collect_log COMMENT='采集日志表';
ALTER TABLE oa_collect_log MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_collect_log MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_collect_log MODIFY COLUMN task_id bigint NOT NULL COMMENT '任务ID';
ALTER TABLE oa_collect_log MODIFY COLUMN status varchar(32) NOT NULL COMMENT '状态';
ALTER TABLE oa_collect_log MODIFY COLUMN start_at timestamp NOT NULL COMMENT '开始时间';
ALTER TABLE oa_collect_log MODIFY COLUMN end_at timestamp DEFAULT NULL COMMENT '结束时间';
ALTER TABLE oa_collect_log MODIFY COLUMN duration_ms bigint DEFAULT NULL COMMENT '耗时(毫秒)';
ALTER TABLE oa_collect_log MODIFY COLUMN record_count int NOT NULL DEFAULT '0' COMMENT '记录数';
ALTER TABLE oa_collect_log MODIFY COLUMN error_message text DEFAULT NULL COMMENT '错误信息';
ALTER TABLE oa_collect_log MODIFY COLUMN retry_count int NOT NULL DEFAULT '0' COMMENT '重试次数';
ALTER TABLE oa_collect_log MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_collect_log MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_collect_log MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_collect_log MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_collect_log MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';
ALTER TABLE oa_collect_log MODIFY COLUMN result_json text DEFAULT NULL COMMENT '结果JSON';

-- ========== oa_collect_task ==========
ALTER TABLE oa_collect_task COMMENT='采集任务表';
ALTER TABLE oa_collect_task MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_collect_task MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_collect_task MODIFY COLUMN task_name varchar(100) NOT NULL COMMENT '任务名称';
ALTER TABLE oa_collect_task MODIFY COLUMN platform_type varchar(32) NOT NULL COMMENT '平台类型';
ALTER TABLE oa_collect_task MODIFY COLUMN account_id bigint NOT NULL COMMENT '账号ID';
ALTER TABLE oa_collect_task MODIFY COLUMN method varchar(32) NOT NULL COMMENT '方法';
ALTER TABLE oa_collect_task MODIFY COLUMN source varchar(32) NOT NULL COMMENT '来源';
ALTER TABLE oa_collect_task MODIFY COLUMN frequency varchar(32) NOT NULL COMMENT '频率';
ALTER TABLE oa_collect_task MODIFY COLUMN cron varchar(64) NOT NULL COMMENT 'Cron表达式';
ALTER TABLE oa_collect_task MODIFY COLUMN api_config_encrypted text DEFAULT NULL COMMENT 'API配置(加密存储)';
ALTER TABLE oa_collect_task MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态';
ALTER TABLE oa_collect_task MODIFY COLUMN last_run_at timestamp DEFAULT NULL COMMENT '最后运行时间';
ALTER TABLE oa_collect_task MODIFY COLUMN next_run_at timestamp DEFAULT NULL COMMENT '下次运行时间';
ALTER TABLE oa_collect_task MODIFY COLUMN run_count int NOT NULL DEFAULT '0' COMMENT '运行次数';
ALTER TABLE oa_collect_task MODIFY COLUMN fail_count int NOT NULL DEFAULT '0' COMMENT '失败次数';
ALTER TABLE oa_collect_task MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_collect_task MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_collect_task MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_collect_task MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_collect_task MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_collector_account_bind ==========
ALTER TABLE oa_collector_account_bind COMMENT='采集器账号绑定表';
ALTER TABLE oa_collector_account_bind MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_collector_account_bind MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_collector_account_bind MODIFY COLUMN last_bind_at timestamp DEFAULT NULL COMMENT 'last_bind时间';
ALTER TABLE oa_collector_account_bind MODIFY COLUMN last_health_check_at timestamp DEFAULT NULL COMMENT 'last_health_check时间';
ALTER TABLE oa_collector_account_bind MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_collector_account_bind MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_collector_account_bind MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_collector_account_bind MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_collector_account_bind MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_config_keyword ==========
ALTER TABLE oa_config_keyword COMMENT='关键词配置表';
ALTER TABLE oa_config_keyword MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_config_keyword MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_config_keyword MODIFY COLUMN platform varchar(50) NOT NULL COMMENT '平台';
ALTER TABLE oa_config_keyword MODIFY COLUMN keyword varchar(100) NOT NULL COMMENT '关键词';
ALTER TABLE oa_config_keyword MODIFY COLUMN match_type varchar(20) NOT NULL DEFAULT 'FUZZY' COMMENT '匹配类型';
ALTER TABLE oa_config_keyword MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态';
ALTER TABLE oa_config_keyword MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_config_keyword MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_config_keyword MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_config_keyword MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_config_keyword MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_content ==========
ALTER TABLE oa_content COMMENT='内容表';
ALTER TABLE oa_content MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_content MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_content MODIFY COLUMN account_id bigint NOT NULL COMMENT '账号ID';
ALTER TABLE oa_content MODIFY COLUMN title varchar(200) NOT NULL COMMENT '标题';
ALTER TABLE oa_content MODIFY COLUMN platform_type varchar(32) NOT NULL COMMENT '平台类型';
ALTER TABLE oa_content MODIFY COLUMN content_type varchar(32) DEFAULT NULL COMMENT '内容类型';
ALTER TABLE oa_content MODIFY COLUMN publish_time timestamp DEFAULT NULL COMMENT '发布时间';
ALTER TABLE oa_content MODIFY COLUMN read_count bigint NOT NULL DEFAULT '0' COMMENT '阅读数';
ALTER TABLE oa_content MODIFY COLUMN like_count int NOT NULL DEFAULT '0' COMMENT '点赞数';
ALTER TABLE oa_content MODIFY COLUMN comment_count int NOT NULL DEFAULT '0' COMMENT '评论数';
ALTER TABLE oa_content MODIFY COLUMN forward_count int NOT NULL DEFAULT '0' COMMENT '转发数';
ALTER TABLE oa_content MODIFY COLUMN is_hit tinyint NOT NULL DEFAULT '0' COMMENT '是否hit';
ALTER TABLE oa_content MODIFY COLUMN data_source varchar(16) NOT NULL DEFAULT 'API' COMMENT '数据来源';
ALTER TABLE oa_content MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'PUBLISHED' COMMENT '状态';
ALTER TABLE oa_content MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_content MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_content MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_content MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_content MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_content_daily ==========
ALTER TABLE oa_content_daily COMMENT='内容日数据表';
ALTER TABLE oa_content_daily MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_content_daily MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_content_daily MODIFY COLUMN content_id bigint NOT NULL COMMENT '内容ID';
ALTER TABLE oa_content_daily MODIFY COLUMN stat_date date NOT NULL COMMENT '统计日期';
ALTER TABLE oa_content_daily MODIFY COLUMN read_count bigint NOT NULL DEFAULT '0' COMMENT '阅读数';
ALTER TABLE oa_content_daily MODIFY COLUMN play_count bigint NOT NULL DEFAULT '0' COMMENT '播放数';
ALTER TABLE oa_content_daily MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_content_daily MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_content_daily MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_content_data_import ==========
ALTER TABLE oa_content_data_import COMMENT='内容数据导入表';
ALTER TABLE oa_content_data_import MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_content_data_import MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_content_data_import MODIFY COLUMN content_id bigint NOT NULL COMMENT '内容ID';
ALTER TABLE oa_content_data_import MODIFY COLUMN stat_date date NOT NULL COMMENT '统计日期';
ALTER TABLE oa_content_data_import MODIFY COLUMN import_type varchar(32) NOT NULL COMMENT 'import_type';
ALTER TABLE oa_content_data_import MODIFY COLUMN read_count bigint DEFAULT NULL COMMENT '阅读数';
ALTER TABLE oa_content_data_import MODIFY COLUMN like_count int DEFAULT NULL COMMENT '点赞数';
ALTER TABLE oa_content_data_import MODIFY COLUMN comment_count int DEFAULT NULL COMMENT '评论数';
ALTER TABLE oa_content_data_import MODIFY COLUMN forward_count int DEFAULT NULL COMMENT '转发数';
ALTER TABLE oa_content_data_import MODIFY COLUMN follower_change int DEFAULT NULL COMMENT 'follower_change';
ALTER TABLE oa_content_data_import MODIFY COLUMN remark varchar(500) DEFAULT NULL COMMENT '备注';
ALTER TABLE oa_content_data_import MODIFY COLUMN reviewer_id bigint DEFAULT NULL COMMENT '审核者ID';
ALTER TABLE oa_content_data_import MODIFY COLUMN review_time timestamp DEFAULT NULL COMMENT '审核时间';
ALTER TABLE oa_content_data_import MODIFY COLUMN submitter_id bigint DEFAULT NULL COMMENT 'SubmitterID';
ALTER TABLE oa_content_data_import MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_content_data_import MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_content_data_import MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_content_data_import MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_content_data_import MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_content_plan ==========
ALTER TABLE oa_content_plan COMMENT='内容计划表';
ALTER TABLE oa_content_plan MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_content_plan MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_content_plan MODIFY COLUMN plan_name varchar(100) NOT NULL COMMENT '计划名称';
ALTER TABLE oa_content_plan MODIFY COLUMN template_id bigint NOT NULL COMMENT '模板ID';
ALTER TABLE oa_content_plan MODIFY COLUMN ip_group_id bigint NOT NULL COMMENT 'IP组ID';
ALTER TABLE oa_content_plan MODIFY COLUMN start_date date NOT NULL COMMENT '开始日期';
ALTER TABLE oa_content_plan MODIFY COLUMN end_date date NOT NULL COMMENT '结束日期';
ALTER TABLE oa_content_plan MODIFY COLUMN description varchar(500) DEFAULT NULL COMMENT '描述';
ALTER TABLE oa_content_plan MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态';
ALTER TABLE oa_content_plan MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_content_plan MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_content_plan MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_content_plan MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_content_plan MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_content_plan_competition ==========
ALTER TABLE oa_content_plan_competition COMMENT='内容计划竞品分析表';
ALTER TABLE oa_content_plan_competition MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_content_plan_competition MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_content_plan_competition MODIFY COLUMN plan_id bigint NOT NULL COMMENT '计划ID';
ALTER TABLE oa_content_plan_competition MODIFY COLUMN competition_id varchar(64) NOT NULL COMMENT '竞品ID';
ALTER TABLE oa_content_plan_competition MODIFY COLUMN competition_name varchar(200) NOT NULL COMMENT 'competition_name';
ALTER TABLE oa_content_plan_competition MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_content_plan_competition MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_content_plan_competition MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_content_plan_competition MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_content_plan_competition MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_content_plan_step ==========
ALTER TABLE oa_content_plan_step COMMENT='内容计划步骤表';
ALTER TABLE oa_content_plan_step MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_content_plan_step MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_content_plan_step MODIFY COLUMN plan_id bigint NOT NULL COMMENT '计划ID';
ALTER TABLE oa_content_plan_step MODIFY COLUMN node_id bigint NOT NULL COMMENT 'NodeID';
ALTER TABLE oa_content_plan_step MODIFY COLUMN scheduled_start timestamp DEFAULT NULL COMMENT 'scheduled_start';
ALTER TABLE oa_content_plan_step MODIFY COLUMN scheduled_end timestamp DEFAULT NULL COMMENT 'scheduled_end';
ALTER TABLE oa_content_plan_step MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_content_plan_step MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_content_plan_step MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_content_plan_step MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_content_plan_step MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_content_publish_record ==========
ALTER TABLE oa_content_publish_record COMMENT='内容发布记录表';
ALTER TABLE oa_content_publish_record MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_content_publish_record MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_content_publish_record MODIFY COLUMN content_id bigint NOT NULL COMMENT '内容ID';
ALTER TABLE oa_content_publish_record MODIFY COLUMN account_id bigint NOT NULL COMMENT '账号ID';
ALTER TABLE oa_content_publish_record MODIFY COLUMN platform_type varchar(32) NOT NULL COMMENT '平台类型';
ALTER TABLE oa_content_publish_record MODIFY COLUMN error_message varchar(500) DEFAULT NULL COMMENT '错误信息';
ALTER TABLE oa_content_publish_record MODIFY COLUMN published_at timestamp DEFAULT NULL COMMENT 'published时间';
ALTER TABLE oa_content_publish_record MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_content_publish_record MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_content_publish_record MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_content_publish_record MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_content_publish_record MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_custom_query ==========
ALTER TABLE oa_custom_query COMMENT='自定义查询表';
ALTER TABLE oa_custom_query MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_custom_query MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_custom_query MODIFY COLUMN query_name varchar(100) NOT NULL COMMENT '查询名称';
ALTER TABLE oa_custom_query MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态';
ALTER TABLE oa_custom_query MODIFY COLUMN sql_text text NOT NULL COMMENT 'sql_text';
ALTER TABLE oa_custom_query MODIFY COLUMN params_json text DEFAULT NULL COMMENT '参数JSON';
ALTER TABLE oa_custom_query MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_custom_query MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_custom_query MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_custom_query MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_custom_query MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_demo_item ==========
ALTER TABLE oa_demo_item COMMENT='演示项目表';
ALTER TABLE oa_demo_item MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_demo_item MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_demo_item MODIFY COLUMN name varchar(128) NOT NULL COMMENT '名称';
ALTER TABLE oa_demo_item MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_demo_item MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_demo_item MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_demo_item MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_demo_item MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_douyin_follower ==========
ALTER TABLE oa_douyin_follower COMMENT='抖音粉丝表';
ALTER TABLE oa_douyin_follower MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_douyin_follower MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_douyin_follower MODIFY COLUMN account_id bigint NOT NULL COMMENT '账号ID';
ALTER TABLE oa_douyin_follower MODIFY COLUMN nickname varchar(200) DEFAULT NULL COMMENT '昵称';
ALTER TABLE oa_douyin_follower MODIFY COLUMN avatar varchar(512) DEFAULT NULL COMMENT '头像';
ALTER TABLE oa_douyin_follower MODIFY COLUMN followed_at timestamp DEFAULT NULL COMMENT 'followed时间';
ALTER TABLE oa_douyin_follower MODIFY COLUMN synced_at timestamp DEFAULT NULL COMMENT '同步时间';
ALTER TABLE oa_douyin_follower MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_douyin_follower MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_douyin_follower MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_douyin_follower MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_douyin_follower MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_douyin_video ==========
ALTER TABLE oa_douyin_video COMMENT='抖音视频表';
ALTER TABLE oa_douyin_video MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_douyin_video MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_douyin_video MODIFY COLUMN account_id bigint NOT NULL COMMENT '账号ID';
ALTER TABLE oa_douyin_video MODIFY COLUMN video_id varchar(64) NOT NULL COMMENT '视频ID';
ALTER TABLE oa_douyin_video MODIFY COLUMN title varchar(500) DEFAULT NULL COMMENT '标题';
ALTER TABLE oa_douyin_video MODIFY COLUMN description varchar(2000) DEFAULT NULL COMMENT '描述';
ALTER TABLE oa_douyin_video MODIFY COLUMN video_url varchar(1024) DEFAULT NULL COMMENT '视频URL';
ALTER TABLE oa_douyin_video MODIFY COLUMN cover_url varchar(1024) DEFAULT NULL COMMENT '封面URL';
ALTER TABLE oa_douyin_video MODIFY COLUMN duration int DEFAULT NULL COMMENT '时长';
ALTER TABLE oa_douyin_video MODIFY COLUMN published_at timestamp DEFAULT NULL COMMENT 'published时间';
ALTER TABLE oa_douyin_video MODIFY COLUMN play_count int DEFAULT NULL COMMENT '播放数';
ALTER TABLE oa_douyin_video MODIFY COLUMN like_count int DEFAULT NULL COMMENT '点赞数';
ALTER TABLE oa_douyin_video MODIFY COLUMN share_count int DEFAULT NULL COMMENT '分享数';
ALTER TABLE oa_douyin_video MODIFY COLUMN comment_count int DEFAULT NULL COMMENT '评论数';
ALTER TABLE oa_douyin_video MODIFY COLUMN collect_count int DEFAULT NULL COMMENT '收藏数';
ALTER TABLE oa_douyin_video MODIFY COLUMN synced_at timestamp DEFAULT NULL COMMENT '同步时间';
ALTER TABLE oa_douyin_video MODIFY COLUMN stats_synced_at timestamp DEFAULT NULL COMMENT 'stats_synced时间';
ALTER TABLE oa_douyin_video MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_douyin_video MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_douyin_video MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_douyin_video MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_douyin_video MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_external_work ==========
ALTER TABLE oa_external_work COMMENT='外部作品表';
ALTER TABLE oa_external_work MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_external_work MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_external_work MODIFY COLUMN account_id bigint DEFAULT NULL COMMENT '账号ID';
ALTER TABLE oa_external_work MODIFY COLUMN platform_type varchar(32) NOT NULL COMMENT '平台类型';
ALTER TABLE oa_external_work MODIFY COLUMN title varchar(200) NOT NULL COMMENT '标题';
ALTER TABLE oa_external_work MODIFY COLUMN work_url varchar(500) DEFAULT NULL COMMENT '作品链接';
ALTER TABLE oa_external_work MODIFY COLUMN play_count bigint NOT NULL DEFAULT '0' COMMENT '播放数';
ALTER TABLE oa_external_work MODIFY COLUMN completion_rate decimal(6,4) DEFAULT NULL COMMENT '完成率';
ALTER TABLE oa_external_work MODIFY COLUMN like_count int NOT NULL DEFAULT '0' COMMENT '点赞数';
ALTER TABLE oa_external_work MODIFY COLUMN publish_time timestamp DEFAULT NULL COMMENT '发布时间';
ALTER TABLE oa_external_work MODIFY COLUMN industry varchar(32) DEFAULT NULL COMMENT 'industry';
ALTER TABLE oa_external_work MODIFY COLUMN ip_group_id bigint DEFAULT NULL COMMENT 'IP组ID';
ALTER TABLE oa_external_work MODIFY COLUMN is_external tinyint NOT NULL DEFAULT '1' COMMENT '是否external';
ALTER TABLE oa_external_work MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_external_work MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_external_work MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_external_work MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_external_work MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_follower_daily ==========
ALTER TABLE oa_follower_daily COMMENT='粉丝日数据表';
ALTER TABLE oa_follower_daily MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_follower_daily MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_follower_daily MODIFY COLUMN account_id bigint NOT NULL COMMENT '账号ID';
ALTER TABLE oa_follower_daily MODIFY COLUMN stat_date date NOT NULL COMMENT '统计日期';
ALTER TABLE oa_follower_daily MODIFY COLUMN follower_count bigint NOT NULL DEFAULT '0' COMMENT '粉丝数';
ALTER TABLE oa_follower_daily MODIFY COLUMN new_follower int NOT NULL DEFAULT '0' COMMENT 'new_follower';
ALTER TABLE oa_follower_daily MODIFY COLUMN unfollow_count int NOT NULL DEFAULT '0' COMMENT '取关数';
ALTER TABLE oa_follower_daily MODIFY COLUMN net_growth int NOT NULL DEFAULT '0' COMMENT 'net_growth';
ALTER TABLE oa_follower_daily MODIFY COLUMN growth_rate decimal(10,4) DEFAULT NULL COMMENT '增长率';
ALTER TABLE oa_follower_daily MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_follower_daily MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_follower_daily MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_funnel_step ==========
ALTER TABLE oa_funnel_step COMMENT='漏斗步骤表';
ALTER TABLE oa_funnel_step MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_funnel_step MODIFY COLUMN funnel_id bigint NOT NULL COMMENT '漏斗ID';
ALTER TABLE oa_funnel_step MODIFY COLUMN step_order int NOT NULL COMMENT 'step_order';
ALTER TABLE oa_funnel_step MODIFY COLUMN event_code varchar(64) NOT NULL COMMENT 'event_code';
ALTER TABLE oa_funnel_step MODIFY COLUMN step_name varchar(100) DEFAULT NULL COMMENT '步骤名称';
ALTER TABLE oa_funnel_step MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_funnel_step MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_funnel_step MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_funnel_step MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_funnel_step MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_home_alert ==========
ALTER TABLE oa_home_alert COMMENT='首页告警表';
ALTER TABLE oa_home_alert MODIFY COLUMN id bigint NOT NULL COMMENT '主键ID';
ALTER TABLE oa_home_alert MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_home_alert MODIFY COLUMN alert_level varchar(32) NOT NULL COMMENT '告警级别';
ALTER TABLE oa_home_alert MODIFY COLUMN alert_content varchar(512) NOT NULL COMMENT 'alert_content';
ALTER TABLE oa_home_alert MODIFY COLUMN alert_source varchar(64) DEFAULT NULL COMMENT 'alert_source';
ALTER TABLE oa_home_alert MODIFY COLUMN trigger_time datetime NOT NULL COMMENT '触发时间';
ALTER TABLE oa_home_alert MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态';
ALTER TABLE oa_home_alert MODIFY COLUMN creator varchar(64) DEFAULT NULL COMMENT '创建者';
ALTER TABLE oa_home_alert MODIFY COLUMN create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_home_alert MODIFY COLUMN updater varchar(64) DEFAULT NULL COMMENT '更新者';
ALTER TABLE oa_home_alert MODIFY COLUMN update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_home_alert MODIFY COLUMN deleted tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_ip_group_anchor_rel ==========
ALTER TABLE oa_ip_group_anchor_rel COMMENT='IP组与主播关联表';
ALTER TABLE oa_ip_group_anchor_rel MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_ip_group_anchor_rel MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_ip_group_anchor_rel MODIFY COLUMN ip_group_id bigint NOT NULL COMMENT 'IP组ID';
ALTER TABLE oa_ip_group_anchor_rel MODIFY COLUMN anchor_user_id bigint NOT NULL COMMENT 'Anchor UserID';
ALTER TABLE oa_ip_group_anchor_rel MODIFY COLUMN anchor_type varchar(16) DEFAULT NULL COMMENT 'anchor_type';
ALTER TABLE oa_ip_group_anchor_rel MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_ip_group_anchor_rel MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_ip_group_anchor_rel MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_ip_group_anchor_rel MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_ip_group_anchor_rel MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_knowledge_base ==========
ALTER TABLE oa_knowledge_base COMMENT='知识库表';
ALTER TABLE oa_knowledge_base MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_knowledge_base MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_knowledge_base MODIFY COLUMN title varchar(100) NOT NULL COMMENT '标题';
ALTER TABLE oa_knowledge_base MODIFY COLUMN category varchar(32) DEFAULT NULL COMMENT '分类';
ALTER TABLE oa_knowledge_base MODIFY COLUMN tags varchar(200) DEFAULT NULL COMMENT '标签';
ALTER TABLE oa_knowledge_base MODIFY COLUMN is_public tinyint NOT NULL DEFAULT '1' COMMENT '是否public';
ALTER TABLE oa_knowledge_base MODIFY COLUMN status tinyint NOT NULL DEFAULT '1' COMMENT '状态';
ALTER TABLE oa_knowledge_base MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_knowledge_base MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_knowledge_base MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_knowledge_base MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_knowledge_base MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_kuaishou_video ==========
ALTER TABLE oa_kuaishou_video COMMENT='快手视频表';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN account_id bigint NOT NULL COMMENT '账号ID';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN title varchar(500) DEFAULT NULL COMMENT '标题';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN description varchar(2000) DEFAULT NULL COMMENT '描述';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN video_url varchar(1024) DEFAULT NULL COMMENT '视频URL';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN cover_url varchar(1024) DEFAULT NULL COMMENT '封面URL';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN duration int DEFAULT NULL COMMENT '时长';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN published_at timestamp DEFAULT NULL COMMENT 'published时间';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN play_count int DEFAULT NULL COMMENT '播放数';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN like_count int DEFAULT NULL COMMENT '点赞数';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN share_count int DEFAULT NULL COMMENT '分享数';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN comment_count int DEFAULT NULL COMMENT '评论数';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN collect_count int DEFAULT NULL COMMENT '收藏数';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN synced_at timestamp DEFAULT NULL COMMENT '同步时间';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN stats_synced_at timestamp DEFAULT NULL COMMENT 'stats_synced时间';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_kuaishou_video MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_layout_import_job ==========
ALTER TABLE oa_layout_import_job COMMENT='版式导入任务表';
ALTER TABLE oa_layout_import_job MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_layout_import_job MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_layout_import_job MODIFY COLUMN source_type varchar(30) NOT NULL COMMENT 'source_type';
ALTER TABLE oa_layout_import_job MODIFY COLUMN source_url varchar(1024) DEFAULT NULL COMMENT 'source_url';
ALTER TABLE oa_layout_import_job MODIFY COLUMN status varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '状态';
ALTER TABLE oa_layout_import_job MODIFY COLUMN preview_layout_json json DEFAULT NULL COMMENT 'preview_layoutJSON数据';
ALTER TABLE oa_layout_import_job MODIFY COLUMN suggested_name varchar(100) DEFAULT NULL COMMENT 'suggested_name';
ALTER TABLE oa_layout_import_job MODIFY COLUMN error_message varchar(500) DEFAULT NULL COMMENT '错误信息';
ALTER TABLE oa_layout_import_job MODIFY COLUMN creator_user_id bigint DEFAULT NULL COMMENT 'Creator UserID';
ALTER TABLE oa_layout_import_job MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_layout_import_job MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_layout_import_job MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_layout_import_job MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_layout_import_job MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';
ALTER TABLE oa_layout_import_job MODIFY COLUMN preview_layout_schema json DEFAULT NULL COMMENT 'preview_layout_schema';
ALTER TABLE oa_layout_import_job MODIFY COLUMN extraction_report json DEFAULT NULL COMMENT 'extraction_report';

-- ========== oa_layout_style ==========
ALTER TABLE oa_layout_style COMMENT='版式样式表';
ALTER TABLE oa_layout_style MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_layout_style MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_layout_style MODIFY COLUMN style_code varchar(64) NOT NULL COMMENT 'style_code';
ALTER TABLE oa_layout_style MODIFY COLUMN name varchar(100) NOT NULL COMMENT '名称';
ALTER TABLE oa_layout_style MODIFY COLUMN tags varchar(200) DEFAULT NULL COMMENT '标签';
ALTER TABLE oa_layout_style MODIFY COLUMN html_snippet longtext NOT NULL COMMENT 'html_snippet';
ALTER TABLE oa_layout_style MODIFY COLUMN thumbnail_file_id bigint DEFAULT NULL COMMENT 'Thumbnail FileID';
ALTER TABLE oa_layout_style MODIFY COLUMN sort int NOT NULL DEFAULT '0' COMMENT '排序';
ALTER TABLE oa_layout_style MODIFY COLUMN status varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态';
ALTER TABLE oa_layout_style MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_layout_style MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_layout_style MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_layout_style MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_layout_style MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_ops_anchor_rel ==========
ALTER TABLE oa_ops_anchor_rel COMMENT='运营主播关联表';
ALTER TABLE oa_ops_anchor_rel MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_ops_anchor_rel MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_ops_anchor_rel MODIFY COLUMN ops_user_id bigint NOT NULL COMMENT 'Ops UserID';
ALTER TABLE oa_ops_anchor_rel MODIFY COLUMN anchor_user_id bigint NOT NULL COMMENT 'Anchor UserID';
ALTER TABLE oa_ops_anchor_rel MODIFY COLUMN ip_group_id bigint DEFAULT NULL COMMENT 'IP组ID';
ALTER TABLE oa_ops_anchor_rel MODIFY COLUMN start_date date NOT NULL COMMENT '开始日期';
ALTER TABLE oa_ops_anchor_rel MODIFY COLUMN end_date date NOT NULL COMMENT '结束日期';
ALTER TABLE oa_ops_anchor_rel MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_ops_anchor_rel MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_ops_anchor_rel MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_ops_anchor_rel MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_ops_anchor_rel MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_order ==========
ALTER TABLE oa_order COMMENT='订单表';
ALTER TABLE oa_order MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_order MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_order MODIFY COLUMN order_no varchar(64) NOT NULL COMMENT '订单号';
ALTER TABLE oa_order MODIFY COLUMN order_amount decimal(16,2) NOT NULL COMMENT '订单金额';
ALTER TABLE oa_order MODIFY COLUMN order_time timestamp NOT NULL COMMENT '订单时间';
ALTER TABLE oa_order MODIFY COLUMN account_id bigint DEFAULT NULL COMMENT '账号ID';
ALTER TABLE oa_order MODIFY COLUMN ip_group_id bigint DEFAULT NULL COMMENT 'IP组ID';
ALTER TABLE oa_order MODIFY COLUMN remark varchar(500) DEFAULT NULL COMMENT '备注';
ALTER TABLE oa_order MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_order MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_order MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_order MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_order MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_order_attribution ==========
ALTER TABLE oa_order_attribution COMMENT='订单归因表';
ALTER TABLE oa_order_attribution MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_order_attribution MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_order_attribution MODIFY COLUMN order_id bigint NOT NULL COMMENT '订单ID';
ALTER TABLE oa_order_attribution MODIFY COLUMN account_id bigint DEFAULT NULL COMMENT '账号ID';
ALTER TABLE oa_order_attribution MODIFY COLUMN ip_group_id bigint DEFAULT NULL COMMENT 'IP组ID';
ALTER TABLE oa_order_attribution MODIFY COLUMN author_id bigint DEFAULT NULL COMMENT '作者ID';
ALTER TABLE oa_order_attribution MODIFY COLUMN ops_user_id bigint DEFAULT NULL COMMENT 'Ops UserID';
ALTER TABLE oa_order_attribution MODIFY COLUMN revenue decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '收入';
ALTER TABLE oa_order_attribution MODIFY COLUMN cost decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '成本';
ALTER TABLE oa_order_attribution MODIFY COLUMN roi decimal(10,4) DEFAULT NULL COMMENT '投资回报率';
ALTER TABLE oa_order_attribution MODIFY COLUMN stat_date date NOT NULL COMMENT '统计日期';
ALTER TABLE oa_order_attribution MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_order_attribution MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_order_attribution MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_order_attribution MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_order_attribution MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_perf_item_record ==========
ALTER TABLE oa_perf_item_record COMMENT='绩效项目记录表';
ALTER TABLE oa_perf_item_record MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_perf_item_record MODIFY COLUMN record_id bigint NOT NULL COMMENT '记录ID';
ALTER TABLE oa_perf_item_record MODIFY COLUMN metric_id bigint NOT NULL COMMENT '指标ID';
ALTER TABLE oa_perf_item_record MODIFY COLUMN metric_value decimal(16,4) DEFAULT NULL COMMENT 'metric_value';
ALTER TABLE oa_perf_item_record MODIFY COLUMN score decimal(8,2) DEFAULT NULL COMMENT 'score';
ALTER TABLE oa_perf_item_record MODIFY COLUMN manual_adjustment decimal(8,2) DEFAULT '0.00' COMMENT 'manual_adjustment';
ALTER TABLE oa_perf_item_record MODIFY COLUMN final_score decimal(8,2) DEFAULT NULL COMMENT 'final_score';
ALTER TABLE oa_perf_item_record MODIFY COLUMN remark varchar(500) DEFAULT NULL COMMENT '备注';
ALTER TABLE oa_perf_item_record MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_perf_item_record MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_perf_item_record MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_perf_item_record MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_perf_item_record MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_perf_record ==========
ALTER TABLE oa_perf_record COMMENT='绩效记录表';
ALTER TABLE oa_perf_record MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_perf_record MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_perf_record MODIFY COLUMN template_id bigint NOT NULL COMMENT '模板ID';
ALTER TABLE oa_perf_record MODIFY COLUMN target_user_id bigint NOT NULL COMMENT 'Target UserID';
ALTER TABLE oa_perf_record MODIFY COLUMN ip_group_id bigint DEFAULT NULL COMMENT 'IP组ID';
ALTER TABLE oa_perf_record MODIFY COLUMN period_type varchar(32) NOT NULL COMMENT '周期类型';
ALTER TABLE oa_perf_record MODIFY COLUMN period_start date NOT NULL COMMENT 'period_start';
ALTER TABLE oa_perf_record MODIFY COLUMN period_end date NOT NULL COMMENT 'period_end';
ALTER TABLE oa_perf_record MODIFY COLUMN total_score decimal(8,2) DEFAULT NULL COMMENT 'total_score';
ALTER TABLE oa_perf_record MODIFY COLUMN grade varchar(8) DEFAULT NULL COMMENT 'grade';
ALTER TABLE oa_perf_record MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态';
ALTER TABLE oa_perf_record MODIFY COLUMN remark varchar(500) DEFAULT NULL COMMENT '备注';
ALTER TABLE oa_perf_record MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_perf_record MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_perf_record MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_perf_record MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_perf_record MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_perf_template_item ==========
ALTER TABLE oa_perf_template_item COMMENT='绩效模板项目表';
ALTER TABLE oa_perf_template_item MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_perf_template_item MODIFY COLUMN template_id bigint NOT NULL COMMENT '模板ID';
ALTER TABLE oa_perf_template_item MODIFY COLUMN metric_id bigint NOT NULL COMMENT '指标ID';
ALTER TABLE oa_perf_template_item MODIFY COLUMN weight decimal(5,2) NOT NULL COMMENT 'weight';
ALTER TABLE oa_perf_template_item MODIFY COLUMN calc_rule varchar(32) NOT NULL DEFAULT 'AUTO' COMMENT 'calc_rule';
ALTER TABLE oa_perf_template_item MODIFY COLUMN score_standard_json text NOT NULL COMMENT 'score_standardJSON数据';
ALTER TABLE oa_perf_template_item MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_perf_template_item MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_perf_template_item MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_perf_template_item MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_perf_template_item MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_personal_wechat_daily_stats ==========
ALTER TABLE oa_personal_wechat_daily_stats COMMENT='个微日统计表';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN personal_wechat_id bigint NOT NULL COMMENT '个人微信ID';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN stat_date date NOT NULL COMMENT '统计日期';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN total_friends int DEFAULT NULL COMMENT 'total_friends';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN new_friends int NOT NULL DEFAULT '0' COMMENT 'new_friends';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN deleted_friends int NOT NULL DEFAULT '0' COMMENT 'deleted_friends';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN messages_sent int NOT NULL DEFAULT '0' COMMENT 'messages_sent';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN messages_received int NOT NULL DEFAULT '0' COMMENT 'messages_received';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN group_count int NOT NULL DEFAULT '0' COMMENT 'group数量';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_personal_wechat_daily_stats MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_platform_account_fan_group ==========
ALTER TABLE oa_platform_account_fan_group COMMENT='平台账号粉丝分组表';
ALTER TABLE oa_platform_account_fan_group MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_platform_account_fan_group MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_platform_account_fan_group MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_platform_account_fan_group MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_platform_account_fan_group MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_platform_account_fan_group MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_platform_account_fan_group MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_private_domain_conversion_bridge ==========
ALTER TABLE oa_private_domain_conversion_bridge COMMENT='私域转化桥接表';
ALTER TABLE oa_private_domain_conversion_bridge MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_private_domain_conversion_bridge MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_private_domain_conversion_bridge MODIFY COLUMN linked_by varchar(64) DEFAULT NULL COMMENT 'linked_by';
ALTER TABLE oa_private_domain_conversion_bridge MODIFY COLUMN linked_at timestamp DEFAULT NULL COMMENT 'linked时间';
ALTER TABLE oa_private_domain_conversion_bridge MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_private_domain_conversion_bridge MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_private_domain_conversion_bridge MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_private_domain_conversion_bridge MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_private_domain_conversion_bridge MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_production_content ==========
ALTER TABLE oa_production_content COMMENT='生产内容表';
ALTER TABLE oa_production_content MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_production_content MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_production_content MODIFY COLUMN title varchar(200) NOT NULL COMMENT '标题';
ALTER TABLE oa_production_content MODIFY COLUMN cover_image varchar(500) DEFAULT NULL COMMENT 'cover_image';
ALTER TABLE oa_production_content MODIFY COLUMN creator_user_id bigint NOT NULL COMMENT 'Creator UserID';
ALTER TABLE oa_production_content MODIFY COLUMN content_type varchar(32) NOT NULL COMMENT '内容类型';
ALTER TABLE oa_production_content MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态';
ALTER TABLE oa_production_content MODIFY COLUMN ai_generated tinyint NOT NULL DEFAULT '0' COMMENT 'ai_generated';
ALTER TABLE oa_production_content MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_production_content MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_production_content MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_production_content MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_production_content MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';
ALTER TABLE oa_production_content MODIFY COLUMN body_format varchar(20) NOT NULL DEFAULT 'PLAIN' COMMENT 'body_format';
ALTER TABLE oa_production_content MODIFY COLUMN layout_json json DEFAULT NULL COMMENT 'layoutJSON数据';
ALTER TABLE oa_production_content MODIFY COLUMN layout_html longtext DEFAULT NULL COMMENT 'layout_html';
ALTER TABLE oa_production_content MODIFY COLUMN layout_template_id bigint DEFAULT NULL COMMENT 'Layout TemplateID';

-- ========== oa_realname_intermediary ==========
ALTER TABLE oa_realname_intermediary COMMENT='实名中间人表';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN realname_id bigint NOT NULL COMMENT '实名ID';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN intermediary_name varchar(64) NOT NULL COMMENT '中间人名称';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN intermediary_phone_encrypted varchar(128) DEFAULT NULL COMMENT 'intermediary_phone(加密存储)';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN intermediary_wechat varchar(64) DEFAULT NULL COMMENT 'intermediary_wechat';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN relation_type varchar(32) NOT NULL COMMENT 'relation_type';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN commission_rate decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT 'commission_rate';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN remark varchar(200) DEFAULT NULL COMMENT '备注';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_realname_intermediary MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_review_record ==========
ALTER TABLE oa_review_record COMMENT='审核记录表';
ALTER TABLE oa_review_record MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_review_record MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_review_record MODIFY COLUMN content_id bigint NOT NULL COMMENT '内容ID';
ALTER TABLE oa_review_record MODIFY COLUMN stage varchar(32) NOT NULL COMMENT 'stage';
ALTER TABLE oa_review_record MODIFY COLUMN action varchar(32) NOT NULL COMMENT '操作动作';
ALTER TABLE oa_review_record MODIFY COLUMN reviewer_id bigint NOT NULL COMMENT '审核者ID';
ALTER TABLE oa_review_record MODIFY COLUMN comment varchar(500) DEFAULT NULL COMMENT 'comment';
ALTER TABLE oa_review_record MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_review_record MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_review_record MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_review_record MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_review_record MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_sop_review ==========
ALTER TABLE oa_sop_review COMMENT='SOP审核表';
ALTER TABLE oa_sop_review MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_sop_review MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_sop_review MODIFY COLUMN task_id bigint NOT NULL COMMENT '任务ID';
ALTER TABLE oa_sop_review MODIFY COLUMN reviewer_id bigint DEFAULT NULL COMMENT '审核者ID';
ALTER TABLE oa_sop_review MODIFY COLUMN reviewer_role varchar(32) DEFAULT NULL COMMENT 'reviewer_role';
ALTER TABLE oa_sop_review MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态';
ALTER TABLE oa_sop_review MODIFY COLUMN comment varchar(500) DEFAULT NULL COMMENT 'comment';
ALTER TABLE oa_sop_review MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_sop_review MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_sop_review MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_sop_review MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_sop_review MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_threshold_config ==========
ALTER TABLE oa_threshold_config COMMENT='阈值配置表';
ALTER TABLE oa_threshold_config MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_threshold_config MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_threshold_config MODIFY COLUMN threshold_category varchar(32) NOT NULL DEFAULT 'ALERT' COMMENT 'threshold_category';
ALTER TABLE oa_threshold_config MODIFY COLUMN threshold_type varchar(20) DEFAULT NULL COMMENT '阈值类型';
ALTER TABLE oa_threshold_config MODIFY COLUMN metric_name varchar(128) NOT NULL COMMENT 'metric_name';
ALTER TABLE oa_threshold_config MODIFY COLUMN metric_type varchar(64) NOT NULL COMMENT 'metric_type';
ALTER TABLE oa_threshold_config MODIFY COLUMN platform_type varchar(64) DEFAULT NULL COMMENT '平台类型';
ALTER TABLE oa_threshold_config MODIFY COLUMN content_type varchar(20) DEFAULT NULL COMMENT '内容类型';
ALTER TABLE oa_threshold_config MODIFY COLUMN judge_mode varchar(10) DEFAULT 'AND' COMMENT 'judge_mode';
ALTER TABLE oa_threshold_config MODIFY COLUMN low_fans bigint DEFAULT NULL COMMENT 'low_fans';
ALTER TABLE oa_threshold_config MODIFY COLUMN high_fans bigint DEFAULT NULL COMMENT 'high_fans';
ALTER TABLE oa_threshold_config MODIFY COLUMN daily_low int DEFAULT NULL COMMENT 'daily_low';
ALTER TABLE oa_threshold_config MODIFY COLUMN daily_high int DEFAULT NULL COMMENT 'daily_high';
ALTER TABLE oa_threshold_config MODIFY COLUMN hot_value bigint DEFAULT NULL COMMENT 'hot_value';
ALTER TABLE oa_threshold_config MODIFY COLUMN low_value bigint DEFAULT NULL COMMENT 'low_value';
ALTER TABLE oa_threshold_config MODIFY COLUMN override_account_id bigint DEFAULT NULL COMMENT 'Override AccountID';
ALTER TABLE oa_threshold_config MODIFY COLUMN override_value bigint DEFAULT NULL COMMENT 'override_value';
ALTER TABLE oa_threshold_config MODIFY COLUMN ip_group_id bigint DEFAULT NULL COMMENT 'IP组ID';
ALTER TABLE oa_threshold_config MODIFY COLUMN compare_operator varchar(16) NOT NULL DEFAULT 'GTE' COMMENT 'compare_operator';
ALTER TABLE oa_threshold_config MODIFY COLUMN threshold_value decimal(18,4) NOT NULL COMMENT '阈值';
ALTER TABLE oa_threshold_config MODIFY COLUMN alert_level varchar(32) NOT NULL DEFAULT 'WARNING' COMMENT '告警级别';
ALTER TABLE oa_threshold_config MODIFY COLUMN notify_methods varchar(256) DEFAULT NULL COMMENT 'notify_methods';
ALTER TABLE oa_threshold_config MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态';
ALTER TABLE oa_threshold_config MODIFY COLUMN remark varchar(512) DEFAULT NULL COMMENT '备注';
ALTER TABLE oa_threshold_config MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_threshold_config MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_threshold_config MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_threshold_config MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_threshold_config MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_typesetting_rule ==========
ALTER TABLE oa_typesetting_rule COMMENT='排版规则表';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN rule_code varchar(64) NOT NULL COMMENT 'rule_code';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN name varchar(100) NOT NULL COMMENT '名称';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN description varchar(500) DEFAULT NULL COMMENT '描述';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN rule_config json NOT NULL COMMENT '规则配置';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN sort int NOT NULL DEFAULT '0' COMMENT '排序';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN status varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_typesetting_rule MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_wechat_layout_template ==========
ALTER TABLE oa_wechat_layout_template COMMENT='微信版式模板表';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN template_name varchar(100) NOT NULL COMMENT '模板名称';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN description varchar(500) DEFAULT NULL COMMENT '描述';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN content_type varchar(20) NOT NULL DEFAULT 'ARTICLE' COMMENT '内容类型';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN layout_json json NOT NULL COMMENT 'layoutJSON数据';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN layout_html longtext DEFAULT NULL COMMENT 'layout_html';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN thumbnail_url varchar(512) DEFAULT NULL COMMENT 'thumbnail_url';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN source_type varchar(30) NOT NULL DEFAULT 'MANUAL' COMMENT 'source_type';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN source_url varchar(1024) DEFAULT NULL COMMENT 'source_url';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN status varchar(20) NOT NULL DEFAULT 'DRAFT' COMMENT '状态';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN creator_user_id bigint NOT NULL COMMENT 'Creator UserID';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN style_css text DEFAULT NULL COMMENT 'style_css';
ALTER TABLE oa_wechat_layout_template MODIFY COLUMN preview_html longtext DEFAULT NULL COMMENT 'preview_html';

-- ========== oa_wechat_mp_article ==========
ALTER TABLE oa_wechat_mp_article COMMENT='微信公众号文章表';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN account_id bigint NOT NULL COMMENT '账号ID';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN article_id varchar(64) NOT NULL COMMENT '文章ID';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN title varchar(500) DEFAULT NULL COMMENT '标题';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN url varchar(1024) DEFAULT NULL COMMENT 'URL地址';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN cover_url varchar(1024) DEFAULT NULL COMMENT '封面URL';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN published_at timestamp DEFAULT NULL COMMENT 'published时间';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN read_count int DEFAULT NULL COMMENT '阅读数';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN like_count int DEFAULT NULL COMMENT '点赞数';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN share_count int DEFAULT NULL COMMENT '分享数';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN synced_at timestamp DEFAULT NULL COMMENT '同步时间';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_wechat_mp_article MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_wechat_mp_follower ==========
ALTER TABLE oa_wechat_mp_follower COMMENT='微信公众号粉丝表';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN account_id bigint NOT NULL COMMENT '账号ID';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN openid varchar(64) NOT NULL COMMENT 'OpenID';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN nickname varchar(200) DEFAULT NULL COMMENT '昵称';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN avatar varchar(512) DEFAULT NULL COMMENT '头像';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN unionid varchar(64) DEFAULT NULL COMMENT 'UnionID';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN subscribed_at timestamp DEFAULT NULL COMMENT 'subscribed时间';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN synced_at timestamp DEFAULT NULL COMMENT '同步时间';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_wechat_mp_follower MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_wechat_official_cert_renewal ==========
ALTER TABLE oa_wechat_official_cert_renewal COMMENT='公众号认证续期表';
ALTER TABLE oa_wechat_official_cert_renewal MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_wechat_official_cert_renewal MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_wechat_official_cert_renewal MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_wechat_official_cert_renewal MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_wechat_official_cert_renewal MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_wechat_official_cert_renewal MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_wechat_official_cert_renewal MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_wechat_video_work ==========
ALTER TABLE oa_wechat_video_work COMMENT='微信视频号作品表';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN account_id bigint NOT NULL COMMENT '账号ID';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN title varchar(500) DEFAULT NULL COMMENT '标题';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN description varchar(2000) DEFAULT NULL COMMENT '描述';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN video_url varchar(1024) DEFAULT NULL COMMENT '视频URL';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN cover_url varchar(1024) DEFAULT NULL COMMENT '封面URL';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN duration int DEFAULT NULL COMMENT '时长';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN published_at timestamp DEFAULT NULL COMMENT 'published时间';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN play_count int DEFAULT NULL COMMENT '播放数';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN like_count int DEFAULT NULL COMMENT '点赞数';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN share_count int DEFAULT NULL COMMENT '分享数';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN comment_count int DEFAULT NULL COMMENT '评论数';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN collect_count int DEFAULT NULL COMMENT '收藏数';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN synced_at timestamp DEFAULT NULL COMMENT '同步时间';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN stats_synced_at timestamp DEFAULT NULL COMMENT 'stats_synced时间';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_wechat_video_work MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_wework_daily_stats ==========
ALTER TABLE oa_wework_daily_stats COMMENT='企微日统计表';
ALTER TABLE oa_wework_daily_stats MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_wework_daily_stats MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_wework_daily_stats MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_wework_daily_stats MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_wework_daily_stats MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_wework_daily_stats MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_wework_daily_stats MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_wework_employee ==========
ALTER TABLE oa_wework_employee COMMENT='企微员工表';
ALTER TABLE oa_wework_employee MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_wework_employee MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_wework_employee MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态';
ALTER TABLE oa_wework_employee MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_wework_employee MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_wework_employee MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_wework_employee MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_wework_employee MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== oa_xiaohongshu_note ==========
ALTER TABLE oa_xiaohongshu_note COMMENT='小红书笔记表';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN account_id bigint NOT NULL COMMENT '账号ID';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN note_id varchar(64) NOT NULL COMMENT '笔记ID';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN xsec_token varchar(256) DEFAULT NULL COMMENT 'xsec_token';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN title varchar(500) DEFAULT NULL COMMENT '标题';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN description varchar(2000) DEFAULT NULL COMMENT '描述';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN note_url varchar(1024) DEFAULT NULL COMMENT '笔记链接';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN cover_url varchar(1024) DEFAULT NULL COMMENT '封面URL';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN published_at timestamp DEFAULT NULL COMMENT 'published时间';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN play_count int DEFAULT NULL COMMENT '播放数';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN like_count int DEFAULT NULL COMMENT '点赞数';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN share_count int DEFAULT NULL COMMENT '分享数';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN comment_count int DEFAULT NULL COMMENT '评论数';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN collect_count int DEFAULT NULL COMMENT '收藏数';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN synced_at timestamp DEFAULT NULL COMMENT '同步时间';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN stats_synced_at timestamp DEFAULT NULL COMMENT 'stats_synced时间';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE oa_xiaohongshu_note MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== sys_dept ==========
ALTER TABLE sys_dept COMMENT='系统部门表';
ALTER TABLE sys_dept MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE sys_dept MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE sys_dept MODIFY COLUMN name varchar(128) NOT NULL COMMENT '名称';
ALTER TABLE sys_dept MODIFY COLUMN sort int NOT NULL DEFAULT '0' COMMENT '排序';
ALTER TABLE sys_dept MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态';
ALTER TABLE sys_dept MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE sys_dept MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE sys_dept MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE sys_dept MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE sys_dept MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== sys_login_log ==========
ALTER TABLE sys_login_log COMMENT='系统登录日志表';
ALTER TABLE sys_login_log MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE sys_login_log MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE sys_login_log MODIFY COLUMN user_id bigint DEFAULT NULL COMMENT '用户ID';
ALTER TABLE sys_login_log MODIFY COLUMN username varchar(64) DEFAULT NULL COMMENT '用户名';
ALTER TABLE sys_login_log MODIFY COLUMN ip varchar(64) DEFAULT NULL COMMENT 'IP地址';
ALTER TABLE sys_login_log MODIFY COLUMN user_agent varchar(512) DEFAULT NULL COMMENT '用户代理';
ALTER TABLE sys_login_log MODIFY COLUMN status varchar(32) NOT NULL COMMENT '状态';
ALTER TABLE sys_login_log MODIFY COLUMN message varchar(512) DEFAULT NULL COMMENT '消息';
ALTER TABLE sys_login_log MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ========== sys_message ==========
ALTER TABLE sys_message COMMENT='系统消息表';
ALTER TABLE sys_message MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE sys_message MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE sys_message MODIFY COLUMN title varchar(256) NOT NULL COMMENT '标题';
ALTER TABLE sys_message MODIFY COLUMN category varchar(32) NOT NULL COMMENT '分类';
ALTER TABLE sys_message MODIFY COLUMN channel varchar(128) DEFAULT NULL COMMENT 'channel';
ALTER TABLE sys_message MODIFY COLUMN receiver varchar(512) NOT NULL COMMENT 'receiver';
ALTER TABLE sys_message MODIFY COLUMN content text NOT NULL COMMENT '内容';
ALTER TABLE sys_message MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态';
ALTER TABLE sys_message MODIFY COLUMN fail_reason varchar(512) DEFAULT NULL COMMENT '失败原因';
ALTER TABLE sys_message MODIFY COLUMN send_time timestamp DEFAULT NULL COMMENT 'send时间';
ALTER TABLE sys_message MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE sys_message MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE sys_message MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE sys_message MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE sys_message MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';
ALTER TABLE sys_message MODIFY COLUMN read_time timestamp DEFAULT NULL COMMENT '阅读时间';

-- ========== sys_metadata_entity ==========
ALTER TABLE sys_metadata_entity COMMENT='系统元数据实体表';
ALTER TABLE sys_metadata_entity MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE sys_metadata_entity MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE sys_metadata_entity MODIFY COLUMN entity_code varchar(64) NOT NULL COMMENT '实体编码';
ALTER TABLE sys_metadata_entity MODIFY COLUMN entity_name varchar(128) NOT NULL COMMENT '实体名称';
ALTER TABLE sys_metadata_entity MODIFY COLUMN physical_table varchar(128) NOT NULL COMMENT '物理表名';
ALTER TABLE sys_metadata_entity MODIFY COLUMN status varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态';
ALTER TABLE sys_metadata_entity MODIFY COLUMN remark varchar(512) DEFAULT NULL COMMENT '备注';
ALTER TABLE sys_metadata_entity MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE sys_metadata_entity MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE sys_metadata_entity MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE sys_metadata_entity MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE sys_metadata_entity MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== sys_metadata_field ==========
ALTER TABLE sys_metadata_field COMMENT='系统元数据字段表';
ALTER TABLE sys_metadata_field MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE sys_metadata_field MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE sys_metadata_field MODIFY COLUMN entity_id bigint NOT NULL COMMENT '实体ID';
ALTER TABLE sys_metadata_field MODIFY COLUMN field_code varchar(64) NOT NULL COMMENT '字段编码';
ALTER TABLE sys_metadata_field MODIFY COLUMN field_name varchar(128) NOT NULL COMMENT '字段名';
ALTER TABLE sys_metadata_field MODIFY COLUMN column_name varchar(128) NOT NULL COMMENT '列名';
ALTER TABLE sys_metadata_field MODIFY COLUMN data_type varchar(32) NOT NULL DEFAULT 'VARCHAR' COMMENT '数据类型';
ALTER TABLE sys_metadata_field MODIFY COLUMN query_condition_type varchar(32) NOT NULL DEFAULT 'TEXT' COMMENT '查询条件类型';
ALTER TABLE sys_metadata_field MODIFY COLUMN dict_type varchar(64) DEFAULT NULL COMMENT '字典类型';
ALTER TABLE sys_metadata_field MODIFY COLUMN selector_config json DEFAULT NULL COMMENT '选择器配置';
ALTER TABLE sys_metadata_field MODIFY COLUMN sort int NOT NULL DEFAULT '0' COMMENT '排序';
ALTER TABLE sys_metadata_field MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE sys_metadata_field MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE sys_metadata_field MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE sys_metadata_field MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE sys_metadata_field MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== sys_notification_event ==========
ALTER TABLE sys_notification_event COMMENT='系统通知事件表';
ALTER TABLE sys_notification_event MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE sys_notification_event MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE sys_notification_event MODIFY COLUMN event_type varchar(64) NOT NULL COMMENT '事件类型';
ALTER TABLE sys_notification_event MODIFY COLUMN biz_key varchar(256) NOT NULL COMMENT '业务键';
ALTER TABLE sys_notification_event MODIFY COLUMN recipient_user_id bigint DEFAULT NULL COMMENT '接收用户ID';
ALTER TABLE sys_notification_event MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ========== sys_operation_log ==========
ALTER TABLE sys_operation_log COMMENT='系统操作日志表';
ALTER TABLE sys_operation_log MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE sys_operation_log MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE sys_operation_log MODIFY COLUMN user_id bigint DEFAULT NULL COMMENT '用户ID';
ALTER TABLE sys_operation_log MODIFY COLUMN username varchar(64) DEFAULT NULL COMMENT '用户名';
ALTER TABLE sys_operation_log MODIFY COLUMN module varchar(64) NOT NULL COMMENT '模块';
ALTER TABLE sys_operation_log MODIFY COLUMN action varchar(64) NOT NULL COMMENT '操作动作';
ALTER TABLE sys_operation_log MODIFY COLUMN level varchar(32) NOT NULL DEFAULT 'INFO' COMMENT '级别';
ALTER TABLE sys_operation_log MODIFY COLUMN content text DEFAULT NULL COMMENT '内容';
ALTER TABLE sys_operation_log MODIFY COLUMN method varchar(256) DEFAULT NULL COMMENT '方法';
ALTER TABLE sys_operation_log MODIFY COLUMN request_params text DEFAULT NULL COMMENT '请求参数';
ALTER TABLE sys_operation_log MODIFY COLUMN response_body text DEFAULT NULL COMMENT '响应体';
ALTER TABLE sys_operation_log MODIFY COLUMN ip varchar(64) DEFAULT NULL COMMENT 'IP地址';
ALTER TABLE sys_operation_log MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'SUCCESS' COMMENT '状态';
ALTER TABLE sys_operation_log MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ========== sys_param ==========
ALTER TABLE sys_param COMMENT='系统参数表';
ALTER TABLE sys_param MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE sys_param MODIFY COLUMN tenant_id bigint NOT NULL COMMENT '租户ID';
ALTER TABLE sys_param MODIFY COLUMN param_name varchar(128) NOT NULL COMMENT '参数名称';
ALTER TABLE sys_param MODIFY COLUMN param_key varchar(128) NOT NULL COMMENT '参数键';
ALTER TABLE sys_param MODIFY COLUMN param_value text NOT NULL COMMENT '参数值';
ALTER TABLE sys_param MODIFY COLUMN param_type varchar(32) NOT NULL DEFAULT 'STRING' COMMENT '参数类型';
ALTER TABLE sys_param MODIFY COLUMN category varchar(32) NOT NULL DEFAULT 'BASIC' COMMENT '分类';
ALTER TABLE sys_param MODIFY COLUMN remark varchar(512) DEFAULT NULL COMMENT '备注';
ALTER TABLE sys_param MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE sys_param MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE sys_param MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE sys_param MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE sys_param MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== sys_permission ==========
ALTER TABLE sys_permission COMMENT='系统权限表';
ALTER TABLE sys_permission MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE sys_permission MODIFY COLUMN code varchar(128) NOT NULL COMMENT '权限编码';
ALTER TABLE sys_permission MODIFY COLUMN name varchar(128) NOT NULL COMMENT '名称';
ALTER TABLE sys_permission MODIFY COLUMN module varchar(64) DEFAULT NULL COMMENT '模块';
ALTER TABLE sys_permission MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE sys_permission MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE sys_permission MODIFY COLUMN updater varchar(64) DEFAULT 'system' COMMENT '更新者';
ALTER TABLE sys_permission MODIFY COLUMN update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE sys_permission MODIFY COLUMN deleted smallint NOT NULL DEFAULT '0' COMMENT '逻辑删除标记(0=未删除,1=已删除)';

-- ========== sys_role_permission ==========
ALTER TABLE sys_role_permission COMMENT='系统角色权限关联表';
ALTER TABLE sys_role_permission MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE sys_role_permission MODIFY COLUMN role_id bigint NOT NULL COMMENT '角色ID';
ALTER TABLE sys_role_permission MODIFY COLUMN permission_id bigint NOT NULL COMMENT '权限ID';
ALTER TABLE sys_role_permission MODIFY COLUMN creator varchar(64) DEFAULT 'system' COMMENT '创建者';
ALTER TABLE sys_role_permission MODIFY COLUMN create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
