-- V135: Restore AUTO_INCREMENT on id columns accidentally stripped by manual V125 comment migration.
-- Symptom: INSERT fails with "Field 'id' doesn't have a default value" (e.g. oa_company/create).

ALTER TABLE oa_company MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '公司ID';
ALTER TABLE oa_company_expansion MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '扩容记录ID';
ALTER TABLE oa_realname MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '实名人ID';
ALTER TABLE oa_phone MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '手机ID';
ALTER TABLE oa_sim_card MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '手机卡ID';
ALTER TABLE oa_account MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '账号ID';
ALTER TABLE oa_account_cost MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '账号成本ID';
ALTER TABLE oa_account_wechat_video_wework_rel MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_dashboard MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_funnel MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_home_alert MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_ip_group MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'IP组ID';
ALTER TABLE oa_ip_group_member MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_metric MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_perf_template MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_personal_wechat_account MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '个人微信账号ID';
ALTER TABLE oa_sop_node MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_sop_template MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_task MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE oa_wework_account MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '企业微信账号ID';
