-- Fix double-encoded UTF-8 in default data-screen dashboards (98601/98602).
-- Root cause: PowerShell/curl wrote UTF-8 bytes misinterpreted as Latin-1 and re-saved.

UPDATE oa_dashboard
SET dashboard_name = '内部运营大屏',
    layout_json = '{"version":1,"scope":"INTERNAL","refreshSeconds":60,"widgets":[{"id":"k1","type":"KPI","title":"作品数","sourceType":"BUILTIN","builtinKey":"work_count"},{"id":"k2","type":"KPI","title":"点赞数","sourceType":"BUILTIN","builtinKey":"like_count"},{"id":"k3","type":"KPI","title":"涨粉数","sourceType":"BUILTIN","builtinKey":"follower_growth"},{"id":"k4","type":"KPI","title":"阅读数","sourceType":"BUILTIN","builtinKey":"read_count"},{"id":"k5","type":"KPI","title":"播放数","sourceType":"BUILTIN","builtinKey":"play_count"},{"id":"s1","type":"STAT","title":"今日新增作品","sourceType":"BUILTIN","builtinKey":"today_content"},{"id":"s2","type":"STAT","title":"今日新增粉丝","sourceType":"BUILTIN","builtinKey":"today_follower"},{"id":"s3","type":"STAT","title":"今日新增订单","sourceType":"BUILTIN","builtinKey":"today_orders"},{"id":"s4","type":"STAT","title":"今日订单金额","sourceType":"BUILTIN","builtinKey":"today_order_amount"},{"id":"s5","type":"STAT","title":"待处理审核","sourceType":"BUILTIN","builtinKey":"pending_review"},{"id":"c1","type":"CHART","title":"多平台粉丝趋势","chartType":"line","sourceType":"BUILTIN","builtinKey":"follower_trend"},{"id":"c2","type":"CHART","title":"内容类型占比","chartType":"pie","sourceType":"BUILTIN","builtinKey":"content_type_pie"},{"id":"c3","type":"CHART","title":"多平台阅读量趋势","chartType":"bar","sourceType":"BUILTIN","builtinKey":"read_trend"},{"id":"l1","type":"LIST","title":"爆款预警（最近24h）","sourceType":"BUILTIN","builtinKey":"hit_works_24h","columns":[{"key":"rank","label":"排名"},{"key":"title","label":"作品标题"},{"key":"read_count","label":"阅读量"},{"key":"trend_pct","label":"趋势"}]}]}',
    updater = 'fix-dashboard-encoding'
WHERE id = 98601;

UPDATE oa_dashboard
SET dashboard_name = '外部竞品大屏',
    layout_json = '{"version":1,"scope":"EXTERNAL","refreshSeconds":60,"widgets":[{"id":"k1","type":"KPI","title":"监控账号总数","sourceType":"BUILTIN","builtinKey":"monitor_accounts"},{"id":"k2","type":"KPI","title":"外部作品总数","sourceType":"BUILTIN","builtinKey":"external_works"},{"id":"k3","type":"KPI","title":"总阅读量/播放量","sourceType":"BUILTIN","builtinKey":"total_plays"},{"id":"k4","type":"KPI","title":"总点赞数","sourceType":"BUILTIN","builtinKey":"total_likes"},{"id":"k5","type":"KPI","title":"24h爆款数","sourceType":"BUILTIN","builtinKey":"hit_24h"},{"id":"k6","type":"KPI","title":"24h低分作品数","sourceType":"BUILTIN","builtinKey":"low_score_24h"},{"id":"c1","type":"CHART","title":"竞品IP主题作品趋势","chartType":"bar","sourceType":"BUILTIN","builtinKey":"ip_theme_trend"},{"id":"l1","type":"LIST","title":"竞品账号粉丝排行 Top10","sourceType":"BUILTIN","builtinKey":"high_follower_top10","columns":[{"key":"rank","label":"排名"},{"key":"account_name","label":"账号名称"},{"key":"platform_type","label":"平台"},{"key":"follower_count","label":"粉丝数"}]},{"id":"l2","type":"LIST","title":"竞品爆款作品（最近24h）","sourceType":"BUILTIN","builtinKey":"external_hit_works","columns":[{"key":"rank","label":"排名"},{"key":"account_name","label":"账号"},{"key":"title","label":"作品标题"},{"key":"play_count","label":"阅读量"},{"key":"like_count","label":"点赞"}]}]}',
    updater = 'fix-dashboard-encoding'
WHERE id = 98602;
